### ISSUE TITLE
Customizer>General Options>General Settings>Content Top/Bottom Padding

### ISSUE THREAD

**Issue by coreypotter** [oceanwp/oceanwp#1]
This works with every non-zero number, but when I set it to zero it reverts back to 50px. The customizer option remains at zero and it displays correctly in the preview, but when you actually load the page outside of the customizer, it is still at 50px. 

![screenshot_013017_084812_pm](https://cloud.githubusercontent.com/assets/12460572/22449342/a12893d2-e72d-11e6-86f1-e9046147eb1b.jpg)

**Comment by oceanwp** [comment]
Hello, sorry for the late reply, I have not received any notification from github.
I have notified this issue, unfortunately I can not do anything, the number 0 is not taken into account in front end because this number is see as null.
If you do not want the margins, you can either remove it via the OceanWP Settings metabox per page/post or for all your site, enter this following css code in the customizer, section Custom CSS/JS:
<pre>body #main #content-wrap { padding-bottom: 0; }</pre>
