### ISSUE TITLE
Re-using styles in a Bootstrap kind of way?

### ISSUE THREAD

**Issue by breath-ee** [oceanwp/oceanwp#106]
I've been used to using Bootstrap for styling custom themes but having found OceanWP it seems to have covered so many variables that re-using common styles must also be possible without the need to bolt [Bootstrap](https://getbootstrap.com/) on top.

Apart from re-using id/class in Elementors panel, I've also used Elementor's shortcode widget for my ContactForm7 (not the OceanWP CF7 widget). But I want to be able to center my button and put two input fields in two columns using the styles OceanWP already has without having to create new ones. 

**ContactForm7 Example: Using OceanWP styles**

```html
<div class="oceanwp-row">
  <div class="col span_1_of_2">
    [text* contact-name placeholder "Name"]
  </div>
  
  <div class="col span_1_of_2">  
    [email* contact-email placeholder "Email"]
  </div>

  [textarea* Message placeholder "Message"]

  [file attache-file limit:5000000 filetypes:pdf|txt|doc|docx]

  <div class="aligncenter">
    [acceptance acceptance-gdpr] By using this form I agree to the conditions outlined in the <a href="#">privacy policy</a>. [/acceptance]

    [submit "Send Message"]
  </div>

</div>
```
_Not sure how to override `padding: 0 10px;` from `.oceanwp-row .col` on my input field ...or if it is even way of correct using .oceanwp-row .col._

The documentation only covers adding [new styles via the customiser](https://docs.oceanwp.org/article/354-add-custom-css-and-js-to-your-website) or using [child theme](https://docs.oceanwp.org/article/90-sample-child-theme) overrides. 

Looking at the `[assets/css/styles.css](https://github.com/oceanwp/oceanwp/blob/master/assets/css/style.css)` it seems to have some common styles for **[FORMS](https://github.com/oceanwp/oceanwp/blob/744b6beeed09bb954f7b058d0e200933b7e89e01/assets/css/style.css#L554)** and there is even a **[Grid > Main Classes](https://github.com/oceanwp/oceanwp/blob/744b6beeed09bb954f7b058d0e200933b7e89e01/assets/css/style.css#L152)** that can be utilised.

Is OceanWP using a popular framework or it is using it's own creation?

Is there any documentation similar to Bootstraps or possibly anything planned covering the use of OceanWP styles outside of the customiser?

**Comment by nicolas-owp** [comment]
Hello, yes it is just some custom css, no framework for this, so you want to add two fields in two columns and add the button full width, right?

**Comment by knightknight** [comment]
Hi @nicolas-owp, that was just an example of having to coded a layout using CF7. If I wanted two input fields in two columns and centered button, what available OceanWP styles do I have? 

I guess my question is if OceanWP is using a custom css is it setup in a way that it can be used like a framework, without needing to add Bootstrap on top or instead of OceanWP css. Is it a custom css that will get some documention? 

Or would it be easier to dequeue a OceanWP theme's CSS file and enqueue bootstrap4 from the child theme, not sure what impact this would have on all the files..?

**Comment by nicolas-owp** [comment]
I don't recommend to load a framework because it will slow down your site.
There is no documentation for this because all users use a page builder so it is easier but it is not complicated at all, for example, if you want fields on two column with the button full width, use this code for your form:

```
<div class="oceanwp-row clr">
<div class="span_1_of_2 col col-1 clr">[text* your-name placeholder "First name"]</div>
<div class="span_1_of_2 col clr">[text text-443 placeholder "Last name"]</div>
<div class="span_1_of_2 col clr">[email* your-email placeholder "Your email"]</div>
<div class="span_1_of_2 col clr">[tel tel-531 placeholder "Your phone"]</div>
</div>

<p>[text your-subject placeholder "Your subject"]</p>

<p>[textarea your-message placeholder "Your message "]</p>

<p style="margin: 0;">[submit class:full "Send Message"]</p>
```

And for the button, you can see that I have added a class named "ful", you just need to add this css code:

```
.full {
    display: block;
    width: 100%;
}
```

**Comment by breath-ee** [comment]
OKay thanks @nicolas-owp.
