### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by zahlio** [oceanwp/oceanwp#175]
We are getting the following error when using chrome Version 74.0.3729.22 (Official Build) dev (64-bit).

It happens when you are using the scroll wheel on your mouse.

**/wp-content/themes/oceanwp/assets/js/main.min.js**
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

It seems to be related to this: https://github.com/oceanwp/oceanwp/blob/0ea55c592fc757366083140b9739539f9d870b77/assets/js/devs/smoothscroll.js#L358

**Comment by EnterpriseBranding** [comment]
@zahlio I noticed this too. If you are using the Extra addon you can disable the smoothscroll script which should get rid of the error for now. Ref: https://oceanwp.org/extension/ocean-extra/

**Comment by shirokoweb** [comment]
Since Chrome 73, the document [level wheel and mousewheel event is set to passive by default](https://developers.google.com/web/updates/2019/02/scrolling-intervention.).

Looks like it has been fixed 3 days ago according to [latest commit](https://github.com/oceanwp/oceanwp/commit/769f07ef81a995c3d7b3bfeb1deedfc69b059732)

Last update on WP repo is [February 15, 2019](https://wordpress.org/themes/oceanwp/) and few versions behind GH commits...

**Comment by shirokoweb** [comment]
@zahlio @EnterpriseBranding I compiled the sources with Grunt. You can find the [main.min.js](https://github.com/shirokoweb/oceanwp/tree/master/build/oceanwp/assets/js) on my fork among all other files up2date should you need to update your theme manually (ftp / WP-CLI)

**Comment by RajeebTheGreat** [comment]
Hi @shirokoweb,

Thank you for your help :)

We'll be updating the theme to include this fix. I'll be closing this issue for now.
