### ISSUE TITLE
Custom Title Background image only login users

### ISSUE THREAD

**Issue by fighterii** [oceanwp/oceanwp#176]
Hello,

i try to set a custom title on my homepage

![background_image](https://user-images.githubusercontent.com/16879286/55069881-4b8e4c00-5085-11e9-8c26-2f6d02dae1de.PNG)

While I'm logged in (as admin) i can see the background image on my homepage just fine.

![logged_in](https://user-images.githubusercontent.com/16879286/55070027-a758d500-5085-11e9-90f5-03ba4d9b4078.PNG)

When i log out, i only see a black background

![not_logged_in](https://user-images.githubusercontent.com/16879286/55070025-a758d500-5085-11e9-8f63-31f9834dfd98.PNG)

**Comment by DynAggelos** [comment]
I have a similar issue (probably related) on a website I manage. For the most part the image I use shows up, but occasionally (inexplicably) the title will have a black background, and the size of the title area will be larger than I want it to be.

It's hard to say what is causing this. It seems to be rather random, and it rarely happens. However, I do think it seems to happen the most on WooCommerce generated pages, or after using URL queries to limit the number of items in the (WC) store. I'm not sure if everyone who visits a page with an OceanWP title will see this happen at the same time, or if it's happening on a per-user-basis.

Although I can't say what is causing this, I'm now fairly certain I know what is happening. It looks to me like the height option is being reset to 300px, and the overlay option is being reset to 1 for a period of time (that's why it's going black, I think). (I say period of time, because sometimes it stays this way across pages for ten minutes or longer, and other times it only happens on one page, and one page load.)

One last thing, I've tried to turn on WP's DEBUG functionality when this black title issue is happening, but it doesn't seem to generate an error log for me.

Here are the specs from the Page Title customization page. Hopefully they are useful.

Visibility: Show On All Devices
Heading Tag: H1
Style: Background Image
Image: ...
Title/Breadcrumb Position: CENTER
Position: Bottom Center
Attachment: Default
Repeat: Repeat-x
Size: Auto
Height (px): 200
Overlay Opacity: 0.1
Overlay Color: #0a0a0a
Padding (px): 34, 34, _
Text Color: _
Enabled Breadcrumbs: True
Position: Absolute Right
Breadcrumb Separator: >
Home Item: ICON
Translation for Homepage: Home
Translation for "404 Not Found": 404 Not Found
Translation for "Search results for": Search results for
Posts Taxonomy: Category
Products Taxonomy: Shop Page
Text Color: #ffffff
Separator Color: #e2e2e2
Link Color: #ffffff
Link Color: Hover: #ffffff

**Comment by fighterii** [comment]
I even managed to get it the other way round:

If i activate Background Image as default style within the Customizer and try to replace it for a specific page with an other title setting, the background image stays active if i'm logged out. If I'm logged in, the custom title is set correctly:

i found out, that while i'm logged out, the custom-style.css looks like this if i'm logged out:
```
.background-image-page-header-overlay {
 opacity:0.2;
 background-color:#ffffff;
}
.page-header {
 background-image: url( https://txxxx.jpg ) !important;
 background-position:center center;
}
/* Header CSS */#site-header.has-header-media .overlay-header-media {
 background-color:#dd9933;
}
```
if i login again it looks like this:

```
/* Header CSS */#site-header.has-header-media .overlay-header-media {
 background-color:#dd9933;
}
```
=> correct


Obviously there must be some problem with creating the custom-stlye.css if i'm not logged in.
=> Caching is deactivated!

**Comment by RajeebTheGreat** [comment]
Hi @fighterii ,

Can you please contact us through pre-purchase question on oceanwp?

**Comment by yamenh79** [comment]
Hello,

I'm facing similar problem. 
When I work on Appearance --> Customize everything looks good and the picture in the background appears with every post. 
But when I open a web page in any browser, the background picture doesn't appear. Instead of a picture there is a black background. 
Below are two screenshots that illustrate the problem

https://ibb.co/WsyxfCp
https://ibb.co/hYbyY0n

My second question is this: Do I have to add a background photo each time in my post settings? Is it possible to automatically display the Featured Image in the background?
