### ISSUE TITLE
Columns in Product Archive conflict in Elementor Pro 2.5

### ISSUE THREAD

**Issue by marcofrasson** [oceanwp/oceanwp#186]
Elementor Pro version 2.5 has modified the use of the WooCommerce product widget. Now they use the default column setting in Appearance> Customize

The problem is that the OceanWP theme does not support this feature, leaving always with 1 columns only. Note that by changing the theme to the WordPress default, the number of columns in Customize is respected.

Issue on github elementor https://github.com/elementor/elementor/issues/7846

See:
[Customize in theme dafault](https://prnt.sc/nbvavo)
[Edit widget Elementor in theme dafault](https://prnt.sc/nbvbjd)

[Customize in OceanWP](https://prnt.sc/nbvbyj)
[Edit widget Elementor in OceanWP](http://prnt.sc/nbvbtx)

**Comment by eramits** [comment]
Hello @marcofrasson,

Sorry for the delay response. Do you still have this issue with the latest version of the theme and Elementor?

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while, so closing this due to lack of details. No similar issues were reported with OceanWP. However, [the same issue has also been reported with the Hello theme itself](https://github.com/elementor/elementor/issues/7846#issuecomment-558341254). Feel free to start a new thread if you're still experiencing problems on your end
