### ISSUE TITLE
Links are not visible anymore in classic editor

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#222]
Hello

Ocean styles for Gutenberg make links in classic editor invisible.
They have no decoration or color, which make them hard to identify.
Can this be fixed?

Thank you

![gutenbergtextdecoration](https://user-images.githubusercontent.com/108828/66923084-827b7d80-f028-11e9-88d9-7c5a9524bec0.PNG)

**Comment by nicomollet** [comment]
@nicolas-owp the repository issues are abandoned since May, can you check them?
Thank you

**Comment by FlyThePlanet** [comment]
> the repository issues are abandoned since May, can you check them?

@nicolas-owp what does it mean?
Is there still any point submitting issues here on Github?
No later than Oct. 2nd, answering a ticket on OceanWP.org Alex asked me to report the issue here on Github

**Comment by nicomollet** [comment]
Well that doesn't look good for Ocean...

**Comment by AlexdeBorba** [comment]
Hello,

Our repository is not abandoned; you may notice that we have been pushing updates to it regularly.

I do not see how OceanWP can be making the links invisible, because I use it extensively while editing and publishing content and never had the same issue, this besides the fact that you are inspecting TinyMCE CSS styles and not OceanWP related inputs as shown on your screenshot.

My recommendation would be to adapt to Gutenburg as support for the Classic Editor will end anytime soon.

You may also try to disable plugins, and activate one by one and see if there is any conflict with your editor.

**Comment by nicomollet** [comment]
Hello @AlexdeBorba 
Issues used to be fixed faster, that's why I am noting a difference.
I do see commit updates, but I was talking about the issues.

Regarding this one, this Ocean style `/wp-content/themes/oceanwp/assets/css/gutenberg/gutenberg-editor.min.css` is loaded in the classic editor and override links with the classes `.mce-content-body a`.

If you don't plan to support Classic Editor, that is good to know, because our team wants to continue using Classic Editor until Gutenberg actually is compatible with all our plugins which is not the case ATM, or not use Gutenberg at all to say the truth.

**Comment by eramits** [comment]
This issue has been fixed in the latest version of the theme.
