### ISSUE TITLE
Schema markup error in your simple product page, how to solve such problem?

### ISSUE THREAD

**Issue by tonytanlh** [oceanwp/oceanwp#225]
Thanks for design an awesome switch for user to turn on or turn off the microdata injection (Schema Markup). 

I would like to check with you, in your simple shop single product, did you turn on the schema markup button or not, as I tested one of your product your product ( https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fsimple.oceanwp.org%2Fproduct%2Fbirdseye-suit-jacket%2F ), found some error of schema markup. 

Please let me know how to solve such error of schema markup. thank you for your attention to this issue.

**Comment by AlexdeBorba** [comment]
Hello @tonytanlh 

You are most welcome and thank you for the feedback.

Even thus we have the enable/disable feature available, regarding Schemas we always recommend our users to use an SEO plugin such as [Rank Math SEO](https://rankmath.com/) in order to extend the functionality and provide better SEO control.

Your errors are related to the fact that we did not have a Brand plugin running on our demos for instance, which can be easily overcome with a proper SEO plugin. Our demos are built for demonstration and preview purposes, therefore, we do not spend time on around SEO.

I hope this answers your question.
