### ISSUE TITLE
Product images are not center align in Gallery Slider option

### ISSUE THREAD

**Issue by lamik** [oceanwp/oceanwp#228]
Hi! I'm facing an issue with image centering while I'm using Slide Gallery for Woocommerce. That issue mostly affects mobile devices, where I'm showing 1 column with products.

![images_not_centered](https://user-images.githubusercontent.com/13315195/68047210-16fb0680-fcde-11e9-989d-331f684b8b75.JPG)

**Comment by lamik** [comment]
I tried to modify CSS but without any results.
.slick-track {
	display:flex !important;
	align-items:center !important;
}

**Comment by eramits** [comment]
Hello @lamik 

For support, please open a support ticket on oceanwp.org. This is place is only for reporting the bug and future requests. 

For the issue you have, it looks like the wrong settings on your site. Please share your site link so that I can check it.

**Comment by MarkHollo** [comment]
Since no similar issues were reported and due to the lack of activity, I will close this thread now.

In case of any problems that require support, please [reach us through our respective support channels](https://docs.oceanwp.org/article/762-how-can-i-get-support).

In case you've found a bug or another issue, please feel free to start a new thread.

Thank you for building with OceanWP
