### ISSUE TITLE
BUG: Elementor and Ocean Extra conflict

### ISSUE THREAD

**Issue by HartLarsson** [oceanwp/oceanwp#24]
I've received many times this error:

post.php?post=67&action=elementor:5056 Uncaught ReferenceError: butterbean is not defined
    at post.php?post=67&action=elementor:5056

I've tried to disabel all plugins and discovered that Ocean Extra has a conflict with the Elementor.
If i disabel OceanExtra the error not appear in console anymore.

I see that anyway i can continue to use the Elementor editor but i want to notice you of this problem in case you want to do a fix.
![image](https://user-images.githubusercontent.com/16102074/33187332-5e6aeeac-d091-11e7-8c89-12d6474f6898.png)

I still using WP 4.8.3 and latest version of Elementor and oceanWP

**Comment by nicolas-owp** [comment]
Hello, I'm aware of this error in the console when you are in the Elementor edit mode, unfortunately, I found no solution to remove it, but don't worry, it cause no conflict with Elementor.

**Comment by lupetalo** [comment]
Oh but it does @nicolas-owp

**Comment by nicolas-owp** [comment]
Hi @lupetalo, if you have a problem with Elementor, it is not because of this. What issue do you have?

**Comment by lupetalo** [comment]
Same error as in OP. But I was able to track it inside child theme to a missing variable... PHP error is causing this...

**Comment by nicolas-owp** [comment]
So you solved the issue?

**Comment by lupetalo** [comment]
Yes, but it is really hard when you get such unrelated error...

**Comment by nicolas-owp** [comment]
Okay.
Feel free to reach me if you have an issue with OceanWP :)

**Comment by lupetalo** [comment]
Ok ill post the same on the Elementor side since I asked on both places. Thanks for the fast response @nicolas-owp

**Comment by nicolas-owp** [comment]
You're welcome :)

**Comment by sonialit** [comment]
Hi there,

I have this issue that I cannot fix. Since I update Elementor and Ocean Extra plugin, my website doesn’t work anymore and I cannot edit anything with Elementor. It’s just a blank page. http://www.sonialisolivagant.com
These are the steps I did:
-Increase my wp memory limit in wp-config file and php.ini file to 256.
-Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
-Did a rollback to the previous Elementor version
-Delete Ocean extra plugin. My website was working, but I need it to do a custom header and other stuff.
-Go to Settings > Permalinks, Change the permalink setting and save, Change the setting back to your original permalink setting and save again

Anyone ?

Thank you a lot.

**Comment by sonialit** [comment]
Oh also @lupetalo ,
Elementor support wrote me this:
I am sorry to inform you but we only have authority to log into WordPress accounts for Elementor Pro users which is why my colleague asked for the email address in your Elementor Pro account.

However, the conflict appears to have been caused by the Ocean Extra plugin and I believe their developers are aware of it: https://github.com/oceanwp/oceanwp/issues/24 though they haven't released a fix to the issue.

It's best to contact and consult with the plugin developer OceanWP regarding the compatibility of their plugin with Elementor.

**Comment by nicolas-owp** [comment]
Hello, I just answered your WordPress topic, we can talk about the issue here or on the WP topic, it is up to you :)
Tell me if the solutions are working.

**Comment by sonialit** [comment]
Hi  @nicolas-owp ! Thanks for the answer on WP topic. But I finally managed to fix the issue.

**Comment by nicolas-owp** [comment]
Hello @sonialit, very glad to hear that, can I know how did you fix the issue? So if another user have the same problem he will know how to fix it thanks to you :)

**Comment by sonialit** [comment]
Hi @nicolas-owp , actuallly, my friend, after going through my website multiple times said to me that it was a wrong setting configuration in the Menu/Header. And that little error caused all of this.

**Comment by nicolas-owp** [comment]
Hi, glad that the issue is solved :)

**Comment by olivermonta** [comment]
Hi @sonialit,
may I ask what exactly was wrong in the Menu/Header that caused the problem. I am facing the same situation that when the OceanExtra Plugin in enabled I cannot edit my pages with Elementor. The page will load forever but I will not gain access to the editing page. Right now I always disable the plugin while I am working on the page but this is not a feasible solution.

**Comment by nicolas-owp** [comment]
Hello @olivermonta, do you use a custom header? Check in the Header > General section of the customizer if you have selected your custom header, then check if you didn't select your custom header in the Header > Menu section.

**Comment by nicolas-owp** [comment]
Hello, okay, can you open a pre-purchase ticket on oceanwp.org and send me the login details of an admin account? I will try to see what is wrong.

**Comment by nicolas-owp** [comment]
Hello, yes, exactly :)

**Comment by Jehu** [comment]
In my case it was a non existing page which was left in the header menu. Removing the broken page from menu solves the problem here.

**Comment by devakali** [comment]
I have the very same issue and it seems to be related to the menu / header settings.

**Comment by nicolas-owp** [comment]
Hello @devakali, do you use a custom header? Check in the Header > General section of the customizer if you have selected your custom header, then check if you didn't select your custom header in the Header > Menu section.

**Comment by Dheeraj-Chouhan** [comment]
Hello Team,
                  i am not able to edit my website, update button not appearing plz help

**Comment by Dheeraj-Chouhan** [comment]
TypeError: Cannot read property 'currentView' of undefined
			at http://rndanalyticals.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.2 - 2:239178
			2018-09-17 12:56 +00:00

**Comment by edraft** [comment]
Found the error :D 

https://github.com/tomusborne/wp-show-posts/blob/master/admin/butterbean/class-butterbean.php

File Location: wp-content/plugins/ocean-extra/include/metabox/butterbean/class-butterbean.php

It´s excatly the part of the error, i couldn´t fix it yet

**Comment by nicolas-owp** [comment]
Hi @edraft, I think it is a different issue, what is your problem exactly?

**Comment by kojilab** [comment]
Having the same error too. OceanWP + Elementor

**Comment by robertglickman** [comment]
I had a similar issue where a single page couldn't be edited. It turned out this error would occur if that page was set as the WordPress posts page (under Settings -> Reading). Unsetting it as the posts page allowed it to be edited with Elementor.
