### ISSUE TITLE
RTL Woocommerce Mobile Issue

### ISSUE THREAD

**Issue by Royb10** [oceanwp/oceanwp#256]
Sort select box is causing white sapce on the left and with unnecessary top margin.

![ocean bug](https://user-images.githubusercontent.com/49725353/74869347-7863e580-5360-11ea-9766-e22611e4906b.png)

**Comment by eramits** [comment]
Hello @Royb10 

Can you please share your site link so that I can check it?

**Comment by Royb10** [comment]
Hi, sure.
This is a demo site I opened: https://demo.rbwise.com/shop/

By the way, there are more issues in the RTL version in Woocommerce topics:
1. The mobile cart is flipped
![Cart](https://user-images.githubusercontent.com/49725353/77537410-b647b280-6ea6-11ea-8396-f8c47a871ade.png)

2.  The menu cart is flipped on mobile:
![cart 2](https://user-images.githubusercontent.com/49725353/77537575-0161c580-6ea7-11ea-9a6e-eb2c601bae5f.png)

**Comment by eramits** [comment]
We will try to fix the RTL issue with the next update of the theme.

**Comment by MarkHollo** [comment]
Hello @Royb10,

Hope all is well. There have been a lot of RTL improvements since the OceanWP 2.0.0 version and we sincerely hope you've been enjoying them.

In case you continue to experience other issues, please place a comment so that we can re-open this thread.

Thank you for building with OceanWP, and for your feedback which helps us make OceanWP better for everyone
