### ISSUE TITLE
Woocommerce infinite scroll - Back to last position issue

### ISSUE THREAD

**Issue by Royb10** [oceanwp/oceanwp#275]
Scenario:
1. User browse the shop
2. Infinite scroll loads products
3. User click on product and enter the single product page
4. User click on BACK button and return to the last position - BUT on this position the products not loaded so actually the user back to the middle of the footer.

This is bad user experience if user need to browse the shop always from top and not from the last position he was.

Link to video: https://streamable.com/ghquxc

**Comment by eramits** [comment]
Hello,

Thank you for reporting it. We will check the issue and try to improve it if possible.

**Comment by Royb10** [comment]
Hi, is there any progress on this issue?

**Comment by MarkHollo** [comment]
Closing this thread because we're unable to replicate the issue and no similar problems were reported in the meantime.

In a couple of days we'll be launching a new version, and if the issue continues on your end, I would recommend opening a support ticket with us on oceanwp.org because the problem requires troubleshooting.

Wishing you a great day
