### ISSUE TITLE
Search Results Found

### ISSUE THREAD

**Issue by ugotta** [oceanwp/oceanwp#297]
https://github.com/oceanwp/oceanwp/blob/33832a5adc0e367ee0c3f3f1e39fb1f19a71c163/languages/zh_CN.po#L226

All "Search Results Found" Should be translated into "找到搜索结果" or "个结果找到"

**Comment by MarkHollo** [comment]
Hello @ugotta,

Thanks for reaching out and apologies for the delayed reply, because we are really not in the position to provide support GitHub as also mentioned here.

Thank you for your translation suggestion. We realize there are many Chinese variations (so far there have not been any complaints), so if the one that is one file does not match your needs, please use the Loco Translate plugin to customize the translation for your website alone. Please remember to update/refresh strings before starting the translation.

Hope this helps and in case of any bugs or problems, please feel free to start a new thread.

Thank you for building with OceanWP
