### ISSUE TITLE
get_cart_contents_count() on Null

### ISSUE THREAD

**Issue by DynAggelos** [oceanwp/oceanwp#306]
Using the most recent version of the theme, I see the following exception in the logs.

```
CRITICAL Uncaught Error: Call to a member function get_cart_contents_count() on null in .../wp-content/themes/oceanwp/inc/woocommerce/woocommerce-helpers.php:58
Stack trace:
#0 .../wp-content/themes/oceanwp/inc/woocommerce/woocommerce-config.php(1927): oceanwp_wcmenucart_menu_item()
#1 .../wp-content/themes/oceanwp/inc/woocommerce/woocommerce-config.php(1873): OceanWP_WooCommerce_Config::get_cart_icon()
#2 .../wp-includes/class-wp-hook.php(287): OceanWP_WooCommerce_Config::menu_cart_icon('<li id="menu-it...', Object(stdClass))
#3 .../wp-includes/plugin.php(206): WP_Hook->apply_filters('<li id="menu-it...', Array)
#4 .../wp-includes/nav-menu-template.php(259): apply_filters('wp_nav_menu_ite...', '<li id="menu-it...', Object(stdClass))
#5 .../wp-content/themes/oceanwp/partials/header/nav.php(162): wp_nav_menu(Obje in .../wp-content/themes/oceanwp/inc/woocommerce/woocommerce-helpers.php on line 58
```

**Comment by NaggingDaivy** [comment]
Hello, is the problem in version 2.0 ?

What happen if you add a product to your cart ? Because the icon does not display correctly on my side.

Here are some screenshots :
https://prntscr.com/vkw6c8
https://prntscr.com/vkw6r6

**Comment by DynAggelos** [comment]
Hi @NaggingDaivy. I believe this was v1.9.0. It was just before OceanWP updated to v2.0.0. I haven't checked if these errors are still happening since the update v2.0.0.

**Comment by FawadNL** [comment]
Using version 2.0.0 and experiencing the same issue

**Comment by MarkHollo** [comment]
Hello @DynAggelos, @FawadNL and @NaggingDaivy,

Thank you all for reaching out and apologies for the delayed reply. Unfortunately, we are really not in the position to provide regular support on GitHub. 

This is a very rare issue that is difficult to replicate, but also related to WooCommerce and [even present in the default StoreFront theme as well, even though they were unable to resolve](https://github.com/woocommerce/storefront/issues/1239). However, we took steps to mitigate this error for OceanWP users and if you're using any of the OceanWP 2.0.1+ versions that problem should not be occurring anymore, neither have further similar issues have been reported.

If you are still experiencing this problem, please let us know in the comment section so that we can re-open this issue.

Thank you all for building with OceanWP
