### ISSUE TITLE
Cart Menu Double Image.

### ISSUE THREAD

**Issue by ktchan1811** [oceanwp/oceanwp#307]
Hi, Good Day.

Have the above issues in my Cart Menu. The following are the Plugins that i used;

1. Elementor Core & Pro
2. Woocommerce
3. SG (Siteground) Optimizer.

I Have been facing this issue when SG Optimizer's Lazy Load is on, but when I off the Lasy Load is back to normal. According to Siteground support team or other post is due to the following as per attached the reply; Just wonder if you can assist on this matter?

"The issue with double images in the cart is related to the Oceanwp theme, which overwrites a few of the WooCommerce templates.

When the lazyload is enabled, we replace the source of the image with a placeholder. In addition, to keep the SEO score, we add a noscript tag with the original image, right after the lazyloaded tag.

Google bots actually runs two waves of indexing across web content, it’s possible some details might be missed. Like lazyloaded images.

Because if JavaScript properly executed, lazy loaded images will not be handled by it and the src attribute is never populated, preventing the browser from starting the download and displaying the images.

This is why we add an additional noscript tag with the original image tag, which will be seen by the bots.

In this case, the theme uses wp_kses function that strips some tags, like noscript tags.

This is why the images are duplicated in the cart."

**Comment by eramits** [comment]
Hello @ktchan1811 

We were not very active on the Github issue page but now we will check it regularly. Regarding the issue, if it is not fixed, kindly share the page URL where your seeing the issue so that I can take a look.

**Comment by MarkHollo** [comment]
Due to lack of feedback, I'm closing this thread.

However, I would like to point something out.
- We have lots of users running sites on SiteGround in combination with the SG Optimizer and image lazy-load option, and this is not the experience they share. The issue could be related to a third-party plugin, a specific setting, a specific setting on Cloudflare even, but it would require troubleshooting.
- The only place we use wp_kses function when it comes to the Mini Cart is the number of items in the basket (in the header itself), therefore totally unrelated to the explanation given, as well as the issue. Everything else is default WooCommerce functions which we have no control over. Then again, it would be a repetitive issue experienced by everyone.
- In a couple of days we'll be launching a completely new version. If the issue happens again, feel free to reach us, either by opening a ticket or by opening a new thread. However, I would recommend a ticket because this requires troubleshooting.

Wishing you a great day
