### ISSUE TITLE
Oceanwp - translation - word not in the .pot file

### ISSUE THREAD

**Issue by seeweb1975** [oceanwp/oceanwp#316]
Anyone got a clue with this? lost a day on that lol

There are somehow 2 words appearing on the theme, where i cannot find them to translate them.1.  Blog and, 2.Post a comment.

It would be of a big help, to tell me not how to translate them but tell me where are those words? in English it self. I looked in the .pot from the theme, from wp and in any plug ins. Every .po file has not this word included. 

Changing to 2020 theme for example, it gets translated. But where looking in the .po of the 2020 themes, there are no "blog or post a comment"

I mean... starting to gt crazy here....  any clue where to look at?

thanks!

**Comment by seeweb1975** [comment]
![where](https://user-images.githubusercontent.com/16323318/105822073-44f3f700-5fc4-11eb-955b-2fcb813a707d.jpg)

No care if we translate this in Chinese or Hebrew... WHERE IS THIS WORD?

**Comment by seeweb1975** [comment]
S O L V E D !!!!!!!!!!!     To avoid other people to suffer..... for the GREEK LANGUAGE, ΤΗΕ LOCALE is not el_GR, as it is written in the WP locale page, but simple     el.   =   el.po !!! THE END

**Comment by MarkHollo** [comment]
Hello @seeweb1975,

Really glad you were able to resolve the problem. To clarify something out - OceanWP doesn't have it's own Greek translation files and this translation is being pulled from WordPress directly, and those are being handled and contributed by volunteers. You can also [contribute to the Greek translation if you have the time](https://translate.wordpress.org/locale/el/default/wp-themes/oceanwp/). If you would like to add missing translations to your website alone, you can also use the Loco Translate plugin. Just remember to update/refresh strings before starting to translate, and make sure to place the translation files (choose this option) directly into the **wp-content** folder, because WP has sometimes issues pulling custom translations from theme or plugin folder.

In case of any other problems or suggestions, please feel free to open a new thread.

Hope this helps and thank you for building with OceanWP
