### ISSUE TITLE
php is outdated. 

### ISSUE THREAD

**Issue by mbrod90** [oceanwp/oceanwp#333]
I am showing that the latest php is 7.4

will there be an update soon?

**Comment by eramits** [comment]
Hi @mbrod90 

I didn't understand it clearly. Where are you seeing it? Also, to update the PHP version, you can always contact your hosting provider.

**Comment by MarkHollo** [comment]
Hello @mbrod90,

I believe this is a misunderstanding of the "lowest PHP version compatibility shown". OceanWP is compatible with the latest version of PHP which is the version no. 8, but we still don't recommend our users using it since it's still an unexplored territory.

In order to use OceanWP, you need to be using at least 7.2 version, which is a minimum threshold assigned by WordPress last summer.

To summarize - PHP is not outdated and OceanWP and Ocean Extensions are compatible with the latest PHP versions.

If you need to change PHP on your website, that's unrelated to any theme you are using and solely dictated by your hosting provider. You have the option to change the PHP version you are running through the cPanel or simply by contacting your hosting provider for support.

In case you experience a different problem, feel free to start a new thread or submit a support ticket. 

Have a great weekend
