### ISSUE TITLE
Translation bug of comments widget

### ISSUE THREAD

**Issue by KisonHe** [oceanwp/oceanwp#352]
The &raquo isn't escaped. 
![Screenshot_20211101_222210](https://user-images.githubusercontent.com/49135678/139687111-35a3c957-6da0-4d2a-9815-c6bd5a91b96c.png)

### What did I try:
1. Modify the file `zh_CN.po` under `wordpress/wp-content/themes/oceanwp/languages`, then generate .mo files. But after apache reload even reboot, nothing happened.
2. So I tried `rm zh_CN.po zh_CN.mo`, strangely after apache reload even reboot, I can still get translations. 

I am not familiar with HTTP stuff, what should I do to improve it? I will be very willing to update translations if I get to know how to.

**Comment by MarkHollo** [comment]
Hello @KisonHe,

The reason you're seeing **& raquo;** instead of the arrows is because someone who did the translation added spacing between the "&" and "raquo;" because that should be one word to display properly "&raquo;"

Please try using the [Loco Translate plugin](https://wordpress.org/plugins/loco-translate/) (it's free) and edit the translation file like described above. If necessary, move the translation file into the SYSTEM folder (an option in Loco Translate) because WordPress sometimes has issues displaying translation files stored in the theme/plugins folder.

Let us know if this worked out for you

**Comment by KisonHe** [comment]
> Hello @KisonHe,
> 
> The reason you're seeing **& raquo;** instead of the arrows is because someone who did the translation added spacing between the "&" and "raquo;" because that should be one word to display properly "»"
> 
> Please try using the [Loco Translate plugin](https://wordpress.org/plugins/loco-translate/) (it's free) and edit the translation file like described above. If necessary, move the translation file into the SYSTEM folder (an option in Loco Translate) because WordPress sometimes has issues displaying translation files stored in the theme/plugins folder.
> 
> Let us know if this worked out for you

OK, the problem is about '＆' and '&', after I change '＆'(FF06) into '&'(0026) everything is fine. Thanks for helping :)
