### ISSUE TITLE
Previous Step Button of Multi-step Checkout Not Working

### ISSUE THREAD

**Issue by pk385** [oceanwp/oceanwp#380]
When using woocommerce(oceanwp 3.2.2) multi-step checkout, it is not possible to go to the previous checkout page after advancing to the billing section without filling out all the required fields which are also required to advance to the next step of checkout.

It seems like the same logic applied to the `next` button is also being applied to the `prev` button. When clicking the `prev` button all required fields are highlighted as if trying to advance to the shipping sections.

It seems like the offending code is here in [woo-multi-step-checkout.js](https://github.com/oceanwp/oceanwp/blob/master/assets/src/js/wp-plugins/woocommerce/woo-multi-step-checkout.js), probably because you're [running validation even on `prev` `data-action` ](https://github.com/oceanwp/oceanwp/blob/fefcc355f5911bbc816806427df5bb97ddc5b714/assets/src/js/wp-plugins/woocommerce/woo-multi-step-checkout.js#L120).

**Comment by MarkHollo** [comment]
Hi there @pk385,

Apologies for the late response here. The problem was indeed resolved, but if you're still experiencing this issue, perhaps it would be best if you could [reach support](https://oceanwp.org/support/) with more details so that we can check what's exactly going on your end.

Thank you very much!
