### ISSUE TITLE
Add social icon for Mastodon

### ISSUE THREAD

**Issue by toedter** [oceanwp/oceanwp#433]
Mastodon (https://mastodon.social/) is an alternative to Twitter that millions of people are already using.
Please add it to the list of social icons.

**Comment by MarkHollo** [comment]
Hi @toedter,

Thanks for reaching out.

If you're using the Font Awesome icons as your main theme icons (Customize > General Options > Theme Icons), you can use a custom code to add the Mastodon [option to the social menus for the Header and Top Bar](https://docs.oceanwp.org/article/365-add-new-social-options-for-the-top-bar-and-the-social-menu).

Unfortunately, the Simple Line Icons library doesn't have an adequate icon, and we would need to order the Mastodon icon for the OceanWP SVG icons library to make a full implementation. Until then, you can make use of the custom code.

Please make sure to add the custom code to the functions.php file of a child theme. You can i[nstall the OceanWP Child theme with one click, directly from the OceanWP Panel, or you can install it the old fashion way](https://docs.oceanwp.org/article/90-sample-child-theme).

Hope this helps as a temporary solution

**Comment by toedter** [comment]
Thanks, I will try it out.

**Comment by toedter** [comment]
Hm, I could not get it working (using OceanWP 3.4.1, free version).

I created a child theme, set the theme icons to 'Font Awesome', then added to functions.php:

``` PHP
function my_ocean_social_options( $array ) {
	// Mastodon icon
	$array['mastodon'] = array(
		'label' => 'Mastodon',
		'icon_class' => 'fab fa-mastodon',
	);

	// Return
	return $array;

}
add_filter( 'ocean_social_options', 'my_ocean_social_options' );
```

=> I can add the mastodon icon to the social bar, but the icon is not displayed correctly, instead I see the text 'fab fa-mastodon'.

When replacing `'icon_class' => 'fab fa-mastodon'` with `'icon_class' => oceanwp_icon( 'mastodon', false)`, I don't see anything.

The fa mastodon icon is rendered correctly if I use `<i class="fab fa-mastodon"></i>` on a page.

**Comment by MarkHollo** [comment]
Hi @toedter,

No worries, it's all good. Just make sure you've registered the icon as well with this function: https://docs.oceanwp.org/article/780-add-new-icons-oceanwp-theme-icons-list

The link is included in the first doc I shared, but it really is easy to miss as well.

Let me know how it goes

**Comment by toedter** [comment]
Thx, but this has no effect, I still see 'fab fa-mastodon' instead of the icon.

Here is my current functions.php:

```php
function my_ocean_social_options( $array ) {
	// Mastodon icon
	$array['mastodon'] = array(
		'label' => 'Mastodon',
		'icon_class' => 'fab fa-mastodon',
	);

	return $array;

}
add_filter( 'ocean_social_options', 'my_ocean_social_options' );

function add_new_icons( $icons ) {
	$icons['mastodon']= array(
                'sili' => 'fab fa-mastodon',
                'fai'  => 'fab fa-mastodon',
                'svg'  => 'fab fa-mastodon',
            ); 

	return $icons;
}
add_filter( 'oceanwp_theme_icons', 'add_new_icons' );
```

**Comment by toedter** [comment]
Implemented this now in https://toedter.com/

**Comment by MarkHollo** [comment]
Hi @toedter,

Happy to hear it worked out! Awesome job!

For social media icons we've always used Font Awesome. So even if you choose Simple Line Icons as the main theme icons, Font Awesome will remain in place for social media. The only difference is when the SVG icons are chosen, but I'm afraid we don't have this file yet.

The Simple Line Icons library is rather limited and not very performant on the front end.

In your case, if you have the FA or SIL chosen as theme icons, and are in a need for new social media options, just follow the same method and add the FA icons for SIL and SVG as well like you already did in the example above, and it'll be awesome.

Don't forget to apply your website for our showcase  (if you want to, of course), because it looks great :) https://oceanwp.org/website-showcase/

Have an amazing weekend!

**Comment by toedter** [comment]
>Don't forget to apply your website for our showcase
Done
