### ISSUE TITLE
Border Box around menu items

### ISSUE THREAD

**Issue by EricRode** [oceanwp/oceanwp#457]
When you click on a menu item a border occurs with the same color as the text. Is it possible to not show this border and make it optional?

**Comment by MarkHollo** [comment]
Hi @EricRode,

For support questions, kindly use:

- WordPress Forum: https://wordpress.org/support/theme/oceanwp/
- OceanWP Facebook Community: https://www.facebook.com/groups/oceanwptheme

This will ensure you always get an answer in time, because 99.9% of topics here are not bugs and we use GitHub for bug reports only.

That being said, it's not a bug, it's a mandatory accessibility styling and we would advise you to leave everything as is.

However, if you do want to remove it, you can use the following CSS which you can add in Customize > Custom CSS / JS > Custom CSS area:

`a:focus { 
outline: 0 !important; 
}`

We look forward to having you join our Community :)

Thanks for choosing OceanWP 🥇
