### ISSUE TITLE
Custom CSS not working

### ISSUE THREAD

**Issue by raulbarriga** [oceanwp/oceanwp#459]
I've added some custom css using the customize section of wordpress, in the custom css/js section, but it's not having any effect on the website, not even when I publish the change. I used a css id selector for the container I wanted to style, even used `!important`, but nothing worked. The id is showing up on dev tools, but not the custom styling, none of it. 

I tried clearing wordpress' cache using hostinger & also clearing chrome's cache, but there was no effect.

Any suggestions?

**Comment by MarkHollo** [comment]
Hi there @raulbarriga,

For support questions, kindly use:

- WordPress Forum: https://wordpress.org/support/theme/oceanwp/
- OceanWP Facebook Community: https://www.facebook.com/groups/oceanwptheme

This will ensure you always get an answer in time, because 99.9% of topics here are not bugs and we use GitHub for bug reports only.

If the CSS is not working on your end, then:
1. you either added CSS in the JS area (it happens), or
2. the CSS you have before the new CSS code added is broken. When a piece of CSS code is broken than all codes added afterwards will not function.

Therefore we can only advise you to check where you added the code and inspect all codes and clear obsolete functions and fix the issues.

If you still experience problems, kindly get in touch with us using one of the available support options and we'd be more than happy to take a look.

Thank you very much and thanks for choosing OceanWP 🥇
