### ISSUE TITLE
Widgets not working after 6.3 Wordpress Update

### ISSUE THREAD

**Issue by cacarios** [oceanwp/oceanwp#461]
I've a child theme installed. After updating Wordpress to 6.3, I cannot customize widgets. When I activate debug mode, I receive a message about incorrect use of wp_enqueue_scripts.

**Comment by MarkHollo** [comment]
Hi @cacarios,

For support questions, kindly use:

- WordPress Forum: https://wordpress.org/support/theme/oceanwp/
- OceanWP Facebook Community: https://www.facebook.com/groups/oceanwptheme

This will ensure you always get an answer in time, because 99.9% of topics here are not bugs and we use GitHub for bug reports only.

That being said, there are still no reports similar to yours and there are no issues with OceanWP or any other Ocean plugins that cause the issue you raised.

I would advise you to check the plugins you have installed and disable all plugins one by one, when the issue is gone you have found the culprit.

If you added some codes in the child theme, I would recommend checking them out and updating per need.

We look forward to you joining our community :)

Thanks for using OceanWP 🥇
