### ISSUE TITLE
The products list doesn't show the price

### ISSUE THREAD

**Issue by lunacer** [oceanwp/oceanwp#479]
I'm trying to set up the product list with WooCommerce.
However, the list prints only two elements: the title and the button to add the cart. 

I looked into the php file and it seems the if condition under the loop inside of the "Display shop and product archive items" is the issue.

If I modify the code, the price shows up.
From:
`if ( 'price-rating' === $element ) { ... }`
to:
`if ( true ) { ... }`

How can I fix this?

**Comment by skalanter** [comment]
Hello @lunacer,

Thank you for reaching out,
Sorry, but I didn't fully understand the main point you were trying to make.

Unfortunately, the information provided here regarding the issue you are facing is insufficient for troubleshooting purposes, and it is impossible to understand why this is happening on your end.

Typically, displaying WooCommerce shortcodes and products as a list works without any issues.
We have also not received any similar reports so far and cannot reproduce any issue related to the display of limited items on our end.

Note: The limited display of elements may be because you have deactivated some of them.
Check out this screenshot: https://postimg.cc/K4vxrYDH.

If you want to customize the theme, you can use the child theme and do the following steps:

By using FTP or cPanel access (if you didn’t use the localhost), Go to this directory: wp-content\themes\oceanwp\
Find the template you want to customize and copy the template file.
Place it on the same path but in the child theme directory and edit codes as you want.

* If you are unfamiliar with PHP, you can contact a PHP expert.
* Please check this screenshot(as an example): https://i.postimg.cc/sxjYTWyt/image.png.
* Download child theme: https://docs.oceanwp.org/article/90-sample-child-theme.
* Developer docs: https://docs.oceanwp.org/collection/19-developer-doc.

_________

**Please note that** if you have any more questions or want to continue this conversation, please join our Facebook group for support. 

We don’t monitor GitHub for support.

Facebook Community Support Group: ​https://www.facebook.com/groups/oceanwptheme/

Thank you for using OceanWP.
Best Regards

**Comment by lunacer** [comment]
Thank you so much for your prompt help.
Your guidance solved my issue. I oversight of the customization settings.

Best regards,
