### ISSUE TITLE
Customizer Theme Buttons Background Color: Hover

### ISSUE THREAD

**Issue by eplanetdesign** [oceanwp/oceanwp#70]
Theme Buttons > Background Color: Hover doesn't seem to work, hover seems to inherit the colors from General Styling > Hover Primary Color.

I even added the theme-button and button classes to the button, still no go.

Thanks

James

**Comment by Laurdet** [comment]
Similar issue. When you change only the Primary Color away from the default settings, all links inherit the Primary color on hover instead of Link Hover color.
It's easy to miss because the default settings for both Primary color and Link Hover are the same color in the default settings.

Is there somewhere that it is defined, which items are controlled by the Primary color?

**Comment by eplanetdesign** [comment]
Working much better but doesn't seem to catch
`button[type="submit"]:hover`
Also, I think the Customizer needs to refresh as changes aren't seen live.

It would be nice if you could add the classes
`a.elementor-button and a.elementor-button:hover`
These work for the Elementor button text and button backgrounds.

It would also be nice to have border and border color for Theme Buttons.

Great theme, excellent work... so much so that I purchased the Unlimited.


Thanks!

James

**Comment by nicolas-owp** [comment]
Hi, thanks, I will fix the button type submit for the next release :)
For Elementor I cannot otherwise it will override the code and as it is very easy to change everything in the Button widget, it is better to leave this as it.

For the border do you want it for all your buttons? I can send you the right css code.

Thanks for the nice words :)

**Comment by kcho55555** [comment]
Hello, 

I faced the same issue and couldnt solve it. I even use css coding and it does not work. 
http://prntscr.com/mkv4wa

The weird thing is that only font color is affected. 

Thanks.

**Comment by nicolas-owp** [comment]
Hello @kcho55555, can you send me the page url where you have this issue?
