### ISSUE TITLE
Feature Request: Full Page Content Width and Content & Sidebar Width

### ISSUE THREAD

**Issue by tannerchung** [oceanwp/oceanwp#92]
There is the ability to determine the content and sidebar widths in the customizer settings, which is great, but the settings to set the content seem to affect both pages that have a sidebar and a pages without a sidebar. Can the field for the content width just be a max content width size setting? This would just allow the sidebar to take priority if it exists and the width to expand the rest of the space until it hits max width.

**Comment by nicolas-owp** [comment]
Hello, unfortunately, with max width it is the same result, what you can do is use a page builder or directly use a css code to set the width if the page is full width.

**Comment by srmahmud2** [comment]
I don't find an option to make a page full-width without the sidebar.

**Comment by skalanter** [comment]
Hello @srmahmud2,

This is a very old and closed thread, and since we don't monitor GitHub for support, kindly join our Facebook community support group via this link: https://www.facebook.com/groups/oceanwptheme/.

However, since version 2.2.0, we have changed meta box settings. In the latest version of OceanWP and Ocean Extra plugin, you can access the new metaboxes from the top right with the "O" icon(aka OceanWP logo). In the general options in OceanWP Settings, you'll see all layouts; also, the same feature for the layout of the website is in the following path: WP Dashboard > Appearance > Customizer >General Options > General Settings.

There is some documentation on how to use the metabox settings. To find them, kindly click on the following link: https://docs.oceanwp.org/article/828-general-main-oceanwp-settings.

For future questions regarding the support, please join our Facebook community: https://www.facebook.com/groups/oceanwptheme/.

Thank you for understanding,
Best Regards
